name: flutter_qrcode
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.10.0
  cupertino_icons: ^1.0.4
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
